//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public int LogNumber { get; set; }
        public string CurrentUser { get; set; }
        public Nullable<int> RentID { get; set; }
        public string TenantName { get; set; }
        public string EmployeeLastName { get; set; }
        public string CenterName { get; set; }
        public string PavilionNumber { get; set; }
        public string StatusCenter { get; set; }
        public Nullable<System.DateTime> RentalStart { get; set; }
        public Nullable<System.DateTime> RentalEnd { get; set; }
    }
}
