//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        public int rentNumber { get; set; }
        public string pavilionNumber { get; set; }
        public int shopCenterNumber { get; set; }
        public int tenantNumber { get; set; }
        public int emloyeeNumber { get; set; }
        public string status { get; set; }
        public System.DateTime rentDateStart { get; set; }
        public System.DateTime rentDateStop { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Pavilions Pavilions { get; set; }
        public virtual Tenants Tenants { get; set; }
    }
}
